### ISSUE TITLE
Savon fails initialize logging properly while running on jruby on windows when the log option is set to false

### ISSUE THREAD

**Issue by rumblinthebronx** [rubiii/savon#2]
``` ruby
Errno::ENOENT: No such file or directory - c:/dev/null
    from org/jruby/RubyFile.java:333:in `initialize'
    from org/jruby/RubyIO.java:1179:in `open'
    from org/jruby/RubyKernel.java:333:in `open'
    from C:/jruby-1.7.1/lib/ruby/1.9/open-uri.rb:35:in `open'
    from C:/jruby-1.7.1/lib/ruby/1.9/logger.rb:599:in `create_logfile'
    from C:/jruby-1.7.1/lib/ruby/1.9/logger.rb:594:in `open_logfile'
    from C:/jruby-1.7.1/lib/ruby/1.9/logger.rb:549:in `initialize'
    from C:/jruby-1.7.1/lib/ruby/1.9/logger.rb:314:in `initialize'
    from C:/jruby-1.7.1/lib/ruby/gems/shared/gems/savon-2.0.2/lib/savon/options.rb:147:in `log'
    from C:/jruby-1.7.1/lib/ruby/gems/shared/gems/savon-2.0.2/lib/savon/options.rb:58:in `initialize'
    from C:/jruby-1.7.1/lib/ruby/gems/shared/gems/savon-2.0.2/lib/savon/client.rb:10:in `initialize'
    from C:/jruby-1.7.1/lib/ruby/gems/shared/gems/savon-2.0.2/lib/savon.rb:8:in `client'

#This is the code thats calling it
    def initialize(options={})
      @mutex = Mutex.new
      options[:namespace_identifier] = :n1
      options[:log] = false
      @client = Savon.client(options)
    end
$ ./jruby --version 
jruby 1.7.1 (1.9.3p327) 2012-12-03 30a153b on Java HotSpot(TM) Client VM 1.6.0_1 
1-b03 [Windows Vista-x86] 
```

**Comment by rubiii** [comment]
thanks for reporting. please post the output of `RUBY_PLATFORM` on your system.

you should be able to work around this problem by creating a custom logger which logs to
the "windows-version" of `/dev/null`. i think.

``` ruby
null_logger = Logger.new("NUL:")
Savon.client(logger: null_logger)
```

related: savonrb/savon#353

**Comment by rumblinthebronx** [comment]
``` ruby
irb(main):006:0> RUBY_PLATFORM
"java"
```

**Comment by rubiii** [comment]
thanks. definitely my mistake, but i learned something new and maybe others can learn from this as well.
please read: http://www.ruby-forum.com/topic/150942

this will be fixed with the next release.

**Comment by rubiii** [comment]
@rumblinthebronx i just pushed a fix to master. could you please let me know whether this works for you?

**Comment by rumblinthebronx** [comment]
Yeah it works now all good.

**Comment by rubiii** [comment]
great. expect this to be fixed with the next release.
